language: node_js
node_js:
  - "6"

branches:
  only:
    - master

script: "npm run build"

before_deploy:
  - npm install
  - mkdir -p deploy
  - mv db.json deploy/db.json

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: junior-recruit-scheduler
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    acl: public_read
    wait-until-deployed: true
    on:
      repo: jojoldu/junior-recruit-scheduler
      branch: master

after_deploy:
  - echo "주니어 개발자 채용 정보 배포 진행중입니다."

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
